# Generated by Django 5.2 on 2025-04-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_report_no', models.CharField(max_length=100)),
                ('work_order_number', models.CharField(max_length=100)),
                ('vessel', models.CharField(max_length=100)),
                ('owner_agent', models.CharField(max_length=100)),
                ('imo_no', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('installation_type', models.CharField(max_length=100)),
                ('engineer', models.CharField(max_length=100)),
                ('reason_for_call', models.TextField()),
                ('job_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
            ],
        ),
    ]
